"""
Pydantic Contracts & Schema Specifications for Telco Churn Platform.
Enforces strict type safety and data integrity between UI, Service Layer, and LLM Agent.
"""

from typing import Any, Optional
from pydantic import BaseModel, Field, field_validator


class CustomerProfile(BaseModel):
    """
    Standard customer payload schema containing raw feature representations.
    """
    customer_id: Optional[str] = Field("CUST-UNKNOWN", description="Unique customer identifier")
    gender: str = Field(..., pattern=r"^(Male|Female)$")
    SeniorCitizen: int = Field(..., ge=0, le=1)
    Partner: str = Field(..., pattern=r"^(Yes|No)$")
    Dependents: str = Field(..., pattern=r"^(Yes|No)$")
    tenure: int = Field(..., ge=0, le=100, description="Months with company")
    PhoneService: str = Field(..., pattern=r"^(Yes|No)$")
    MultipleLines: str = Field(..., pattern=r"^(Yes|No|No phone service)$")
    InternetService: str = Field(..., pattern=r"^(DSL|Fiber optic|No)$")
    OnlineSecurity: str = Field(..., pattern=r"^(Yes|No|No internet service)$")
    OnlineBackup: str = Field(..., pattern=r"^(Yes|No|No internet service)$")
    DeviceProtection: str = Field(..., pattern=r"^(Yes|No|No internet service)$")
    TechSupport: str = Field(..., pattern=r"^(Yes|No|No internet service)$")
    StreamingTV: str = Field(..., pattern=r"^(Yes|No|No internet service)$")
    StreamingMovies: str = Field(..., pattern=r"^(Yes|No|No internet service)$")
    Contract: str = Field(..., pattern=r"^(Month-to-month|One year|Two year)$")
    PaperlessBilling: str = Field(..., pattern=r"^(Yes|No)$")
    PaymentMethod: str = Field(
        ...,
        pattern=r"^(Electronic check|Mailed check|Bank transfer \(automatic\)|Credit card \(automatic\))$",
    )
    MonthlyCharges: float = Field(..., ge=10.0, le=200.0)
    TotalCharges: float = Field(..., ge=0.0, le=10000.0)

    @field_validator("TotalCharges", mode="before")
    @classmethod
    def parse_total_charges(cls, v: Any) -> float:
        if isinstance(v, str):
            v_clean = v.strip()
            if v_clean == "":
                return 0.0
            return float(v_clean)
        return float(v)


class InferenceResult(BaseModel):
    """
    Evaluation output of the machine learning inference pipeline.
    """
    customer_id: str = "CUST-UNKNOWN"
    churn_probability: float = Field(..., ge=0.0, le=1.0)
    optimal_threshold: float = Field(0.39, ge=0.0, le=1.0)
    decision: str = Field(..., pattern=r"^(INTERVENE|DO_NOT_INTERVENE)$")
    expected_loss: float = Field(..., ge=0.0)
    risk_level: str = Field(..., pattern=r"^(HIGH_RISK|MODERATE_RISK|LOW_RISK)$")


class SHAPFactor(BaseModel):
    """
    Individual feature contribution extracted from TreeSHAP.
    """
    feature_name: str
    feature_value: str
    shap_value: float
    impact_type: str = Field(..., pattern=r"^(RISK_DRIVER|RETENTION_ANCHOR)$")
    human_explanation: str


class CustomerDiagnostic(BaseModel):
    """
    Composite explainability context containing raw profile, ML score, and SHAP contributors.
    """
    customer: CustomerProfile
    baseline_churn_prob: float
    decision_threshold: float = 0.39
    is_at_risk: bool
    top_risk_drivers: list[SHAPFactor]
    top_retention_anchors: list[SHAPFactor]

    @field_validator("customer", mode="before")
    @classmethod
    def coerce_customer(cls, v: Any) -> Any:
        if hasattr(v, "model_dump"):
            return v.model_dump()
        return v


class RetentionPerk(BaseModel):
    """
    Catalog item representing an approved corporate retention initiative.
    """
    perk_id: str
    name: str
    description: str
    cost_usd: float = Field(..., le=20.0, description="Cost must not exceed unit economic margin ($20)")
    feature_patch: dict[str, Any] = Field(..., description="Feature transformation simulated in ML model")
    target_drivers: list[str] = Field(..., description="SHAP features addressed by this perk")


class RetentionPlan(BaseModel):
    """
    Structured response contract generated by Agentic AI or Heuristic Fallback Engine.
    """
    root_cause_diagnosis: str = Field(
        ...,
        description="Ringkasan 2 kalimat tentang akar penyebab risiko churn berdasarkan nilai SHAP tertinggi."
    )
    recommended_package_name: str = Field(
        ...,
        description="Nama program retensi resmi yang ditawarkan kepada pelanggan."
    )
    incentive_cost_usd: float = Field(
        ...,
        le=20.0,
        description="Total biaya program/diskon untuk perusahaan (wajib <= $20.00)."
    )
    simulated_churn_prob: float = Field(
        ...,
        description="Probabilitas churn baru hasil komputasi pipeline ML setelah modifikasi fitur."
    )
    risk_reduction_pct: float = Field(
        ...,
        description="Persentase penurunan risiko churn: ((P_old - P_new) / P_old) * 100%."
    )
    projected_net_value_usd: float = Field(
        ...,
        description="Estimasi nilai keuntungan bersih yang diselamatkan perusahaan melalui intervensi ini."
    )
    outreach_script: str = Field(
        ...,
        description="Naskah percakapan empati dan persuasif untuk staf retensi via telepon atau WhatsApp."
    )
    confidence_level: str = Field(
        ...,
        pattern=r"^(HIGH|MEDIUM|LOW)$",
        description="Tingkat kepercayaan agen terhadap keberhasilan rencana berdasarkan data."
    )
    generation_source: str = Field(
        "OPENROUTER_AGENT",
        pattern=r"^(OPENROUTER_AGENT|GEMINI_AGENT|PYDANTIC_AI_AGENT|HEURISTIC_FALLBACK)$",
        description="Sumber eksekusi strategi: Live AI atau Fallback Rule Engine."
    )
